### ISSUE TITLE
Issue with Android Auto

### ISSUE THREAD

**Issue by hartator** [Trevelopment/MZD-AIO-TI#10] opened 2017-01-06 02:37 UTC
Thanks for awesome work, you guys are truly amazing. 

I am getting some issues with Android Auto. It seems to have paired fine. The Android App from the car and the phone seem to recognize each other fine. Like when I unplug the usb, I am getting some lines about not been able to connect to the device.

However, the screen - after showing up credit - is staying black.

I've followed all the instructions I think correctly plus already tried to reboot everything several times.

Any ideas to fix that?

Running Mazda3 on v55.00.760A-NA.
OnePlus 3T running Android 6.0.1 + Last AA 2.0.642704.

**Comment by Trevelopment** [comment] 2017-01-06 02:49
I have been hearing about this problem and will release an update with a fix in the next few days.  If you want to test the fix before then [go here](https://aio.trevelopment.win/tester).  (If you test it, let me know if it works for you)

**Comment by bdr99** [comment] 2017-01-06 05:51
I tried to use the test version but I got the following error:
![image](https://cloud.githubusercontent.com/assets/2292715/21708836/2fafde04-d3aa-11e6-8761-35f3d5567de6.png)

**Comment by bdr99** [comment] 2017-01-06 06:56
I saw that you renamed the 0-byte file `_helloworldApp.css` to `_androidautoApp.css` in `config\androidauto\jci\gui\apps\_androidauto\css`. Is this what was supposed to fix the black screen problem?

**Comment by Trevelopment** [comment] 2017-01-06 07:02
I also found a file with EOL of CRLF and I think all files with text 
should be EOL of LF

~ Ŧ®ḝź
------------------------------------------------------------------------
MazdaTweaks.com | AIO -- All In One Tweaks <http://mazdatweaks.com>
------------------------------------------------------------------------

**Comment by bdr99** [comment] 2017-01-06 07:31
OK, I understand. Do you know why I would be receiving the error message in
my screenshot above?

**Comment by Trevelopment** [comment] 2017-01-06 07:36
I was developing something and didn't put in the catch for that error yet.  try the link again I just uploaded a new file.

**Comment by Trevelopment** [comment] 2017-01-06 07:49
[Here is the link again](https://aio.trevelopment.com/tester)

**Comment by shanep2300** [comment] 2017-01-06 13:09
Link is dead.

**Comment by hartator** [comment] 2017-01-06 17:03
Same here, both links do 404.

**Comment by bdr99** [comment] 2017-01-06 17:05
I think the link for the test version was removed because it was officially released as version 2.1.0. The main download link (http://dl.mazdatweaks.win/) now points to 2.1.0.

**Comment by hartator** [comment] 2017-01-06 21:38
Thanks!

Tried to install `2.1.0` via USB, nothing happen when plugged in the car unfortunately. 

Stupid question. Do I need to uninstall the previous Android Auto first or it's okay to override?

**Comment by Trevelopment** [comment] 2017-01-06 21:42
You can override it will also delete any old AA files if they exist.

**Comment by shanep2300** [comment] 2017-01-06 23:51
Yup, can confirm that nothing happened when I plugged in the USB with the 2.1.0 AA tweak.

**Comment by Trevelopment** [comment] 2017-01-11 23:06
**Fixed in the update** A few people have confirmed it's working.  Let me know if it works for you and I will close this issue.

**Comment by Funsh** [comment] 2017-01-16 06:40
Tried over the weekend to install AA with 2.1.3 and it didn't work.
The popup window just stays there for like 5-10 minutes and then disappears (as if you would press the OK on the touchscreen)
The first time i tried to install it with all the other tweaks and it didn't work.
After that i tried to just remove AA (get rid of the copied files; without touching any of the other tweaks) and it also does nothing.

Tried today installing AA again (only AA, nothing else) and it shows the same behavior.
All atempts were made without pressing anything (except for the Yes at the beginning) and letting it run for ~20-30 minutes.

**Comment by Trevelopment** [comment] 2017-01-16 10:59
So are you saying the installation never finishes?

**Comment by Funsh** [comment] 2017-01-16 11:36
To me it seems that it never finishes (or it doesn't even starT)
I installed the rest of the tweaks without AA and it finishes normally and reboots the radio properly.
With AA it just brings the popup on the radio that it is installing AA, but nothing happens.

Attached is a logfile that i made this morning while driving to work, where i uninstalled the 1 second diagnostic menu and the bigger album art and tried to install AA.
I kept the stick in the radio ~30min after installation start of AA (thats aproximately how long it takes to drive to work).
According to the logfile nothing happens, although i do not know what the AA install writes into the logfile
[AIO_log.txt](https://github.com/Trevelopment/MZD-AIO-TI/files/708185/AIO_log.txt)

**Comment by ryansomerfield1** [comment] 2017-01-16 12:38
I can confirm that AA does not install - nor does the system reboot (presumably because the install never finishes).

**Comment by Trevelopment** [comment] 2017-01-18 02:11
Update

**Comment by Funsh** [comment] 2017-01-18 06:36
Thanks for the update.
For me the installation worked with 2.1.5

**Comment by Trevelopment** [comment] 2017-01-18 09:06
Sweet

**Comment by Funsh** [comment] 2017-01-18 19:31
I am not sure that it is fully resolved yet. Maybe it is also just a user error.
Never had AA running before, so i don't know what to expect.

2.1.5 installed it, it shows up to select and start. But when I try to start it it simply shows the window with teh credits and only two lines in the status window:
Not_Running
END

I tried already everything i could think of (USB debugging on/off, mtp/just charging, reinstalled android auto on the phone a few times, different usb cables, different bluetooth settings, different timings when connecting the phone/starting AA on the radio, ...), but it always just calls out the above message.

So i am not sure what it should say if it doesn't detect the phone properly.
If this message is normal when the communication to the phone is not done then i have to investigate further.

Could it be that this message is a indicator that something hasn't installed properly? Maybe a file was not copied properly or a modification was not made?

Attached is the logfile from installing it. Unfortunately it doesn't tell me if all files are on the radio that should be there.
[AIO_log.txt](https://github.com/Trevelopment/MZD-AIO-TI/files/714828/AIO_log.txt)

**Comment by shanep2300** [comment] 2017-01-18 19:47
@Funsh Ok, I was just about to ask if it actually works once you installed it, because that's the original problem of this issue. I haven't tried it yet, but I'll give it a shot by the end of this week to verify.

**Comment by Trevelopment** [comment] 2017-01-18 23:06
I will reopen this and see if @khantaena knows about any issues like this

**Comment by ryansomerfield1** [comment] 2017-01-18 23:12
I'm also having the same problem... Thank you so much for looking into it!

On Jan 18, 2017 6:06 PM, "Trezdog44" <notifications@github.com> wrote:

Reopened #10 <https://github.com/Trevelopment/MZD-AIO-TI/issues/10>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Trevelopment/MZD-AIO-TI/issues/10#event-928306740>, or mute
the thread

**Comment by Trevelopment** [comment] 2017-01-19 03:11
[You Guys Can Test This](https://trevelopment.win/tester)
OK so here's what I did:
<https://github.com/gartnera/headunit> is the ported AA so I downloaded the repo and replaced all the binary files. Hopefully that does the trick.

**Comment by Funsh** [comment] 2017-01-19 06:03
Tried to use the test version, unfortunately it creates the same issue (Not_running ; End).
I also compared the AA files between the versions (2.1.5 and 2.1.5 test) and all of the files are the same (filesize, crc), except the headunit-wrapper, which has a small difference (a few lines of code).

**Comment by Trevelopment** [comment] 2017-01-19 07:03
[Here's One more for you tonight](https://trevelopment.win/tester) it includes #17 from @khantaena

**Comment by ryansomerfield1** [comment] 2017-01-19 14:09
Woohoo! It works! I've noticed some minor bugs (AA not recognizing if bluetooth is on to make calls, etc) but these may be existing issues. Otherwise it's working well! Thank you @Trevelopment !

**Comment by Funsh** [comment] 2017-01-19 16:39
Can confirm, it works great.

**Comment by Trevelopment** [comment] 2017-01-19 22:50
Sweeeeeet thanks to @khantaena as well for helping figure out that barrel of monkeys

**Closed by Trevelopment** 2017-01-19 22:50 UTC
